# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.cannedreporting.com
title: InterLink Marketing
email: jeff@interlinkmg.com
author: Kevin Pettit
description: > # "Write an awesome description for your new site here. 
  InterLink Marketing Pleaston, California

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/pages/InterLink-Marketing-Group/156500074410126

